INSERT INTO Artist (name, bio) VALUES ('Bones', '∞')
INSERT INTO Artist (name, bio) VALUES ('plenka', '∞')
INSERT INTO Artist (name, bio) VALUES ('satanwave x plenka', '∞')
INSERT INTO Artist (name, bio) VALUES ('plenka x CRASPORE', '∞')
INSERT INTO Artist (name, bio) VALUES ('plenka x G.U.I.L.T', '∞')
INSERT INTO Artist (name, bio) VALUES ('plenka x Gnothi Seauton', '∞')
INSERT INTO Artist (name, bio) VALUES ('Depeche Mode', '∞')
INSERT INTO Artist (name, bio) VALUES ('Joy Division', '∞')
INSERT INTO Artist (name, bio) VALUES ('Eminem', '∞')
INSERT INTO Artist (name, bio) VALUES ('Oh Wonder', '∞')
INSERT INTO Artist (name, bio) VALUES ('BROCKHAMPTON', '∞')
INSERT INTO Artist (name, bio) VALUES ('XXXTENTACION', '∞')
INSERT INTO Artist (name, bio) VALUES ('Кровосток', '∞')
INSERT INTO Artist (name, bio) VALUES ('Arctic Monkeys', '∞')
INSERT INTO Artist (name, bio) VALUES ('Frank Sinatra', '∞')
INSERT INTO Artist (name, bio) VALUES ('Кино', '∞')
INSERT INTO Artist (name, bio) VALUES ('HONNE', '∞')
INSERT INTO Artist (name, bio) VALUES ('The Neighbourhood', '∞')
INSERT INTO Artist (name, bio) VALUES ('The Doors', '∞')
INSERT INTO Artist (name, bio) VALUES ('NF', '∞')
INSERT INTO Artist (name, bio) VALUES ('Red Hot Chili Peppers', '∞')
INSERT INTO Artist (name, bio) VALUES ('Milky Chance', '∞')