INSERT INTO Album (name, artistId, genreId, description) VALUES ('IFeelLikeDirt', 1, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('plenka', 2, 2, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Filament', 2, 2, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('reboot', 2, 2, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('пl3nk', 2, 2, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('KickingTheBucket', 1, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('UnderTheWillowTree', 1, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('TheManInTheRadiator', 1, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('LivingSucks', 1, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('PaidProgramming2', 1, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Exciter', 7, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Music for the Masses', 7, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Unknown Pleasures', 8, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Closer', 8, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Kamikaze', 9, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('The Marshall Mathers LP2', 9, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('The Marshall Mathers LP', 9, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Oh Wonder', 10, 4, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Ultralife', 10, 4, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('GINGER', 11, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('iridescence', 11, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('SATURATION', 11, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('SATURATION II', 11, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Bad Vibes Forever', 12, 5, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('?', 12, 5, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('17', 12, 5, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('ЧБ', 13, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Студень', 13, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Гантеля', 13, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Suck it and see', 14, 6, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Tranquility Base Hotel & Casino', 14, 6, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('AM', 14, 6, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Love and Marriage', 15, 7, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Легенда', 16, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Warm', 17, 8, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Love me', 17, 8, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('I Love You', 18, 6, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Hard To Imagine', 18, 6, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('#000000 & #FFFFFF', 18, 6, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('L.A. Woman', 19, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Morrison Hotel', 19, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Waiting for the Sun', 19, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('The Doors', 19, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('NF', 20, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Mansion', 20, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Therapy Session', 20, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('The Search', 20, 1, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('The Studio Album Collection', 21, 3, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Blossom', 22, 4, '∞');
INSERT INTO Album (name, artistId, genreId, description) VALUES ('Mind The Moon', 22, 4, '∞');