INSERT INTO Track (title, artistId, albumId, duration) VALUES ('IFeelLikeDirt', 1, 1, 107);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FrostBite', 1, 1, 131);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Chrome', 1, 1, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('AirplaneMode', 1, 1, 75);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SingingInTheRain', 1, 1, 138);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ArentYouASightForSoreEye', 1, 1, 132);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TimeIsNotOnMySide', 1, 1, 68);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('517', 1, 1, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('PalmDrive', 1, 1, 125);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WhenWasTheLastTime', 1, 1, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Offense,NoneTaken', 1, 1, 121);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BlindHarper', 1, 1, 109);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TheJokesOnYou', 1, 1, 172);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TriviaNight', 1, 1, 136);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('KickingTheBucket', 1, 6, 34);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Mortuary', 1, 6, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SexualHarassmentInTheWorkPlace', 1, 6, 112);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BodyCloseToMine', 1, 6, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('CallMeBackWhenYouGetThis', 1, 6, 169);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('48843', 1, 6, 114);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('KnockOnWood', 1, 6, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Carhartt', 1, 6, 73);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('DontLookDown', 1, 6, 147);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('AllDressedUpToGoDreaming', 1, 6, 107);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WideAwake', 1, 6, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('OneMansTrashIsAnotherMansTreasure', 1, 6, 152);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('UnderTheWillowTree', 1, 7, 57);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SixFeetDeep', 1, 7, 117);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('RedRover', 1, 7, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Titanium', 1, 7, 86);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Holland', 1, 7, 99);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ChokeHold', 1, 7, 99);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('KnuckleSandwich', 1, 7, 95);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Eiffel65', 1, 7, 88);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TimeFliesWhenYoureHavingFun', 1, 7, 135);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Pufferfish', 1, 7, 104);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LastOneThereIsARottenEgg', 1, 7, 125);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TheOppositeOfUp', 1, 7, 170);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('PuttingMyBestFootForward', 1, 7, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lithium', 1, 7, 111);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Precipitation', 1, 7, 157);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('CompetitiveCooldown', 1, 7, 111);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SameOldStory', 1, 7, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WhatHaveYouDoneForMeLately', 1, 7, 130);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('AsIRovedOut', 1, 7, 130);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TheMomentIMetTrueFear', 1, 8, 181);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WatchingPaintDry', 1, 8, 117);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NotOnMyWatch', 1, 8, 148);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ThisGameIsRigged', 1, 8, 114);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TellMeSomethingIDontKnow', 1, 8, 188);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('4x4', 1, 8, 149);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BetterSafeThanSorry', 1, 8, 110);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lights', 1, 8, 121);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BluntGutSonata', 1, 8, 103);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('HowToRobAGrave', 1, 8, 139);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('IAmTheOneHidingUnderYourBed', 1, 8, 174);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TomorrowSeemsSoFarAway', 1, 8, 135);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('RightClickSaveIt', 1, 8, 116);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MyHeart,ItHurts', 1, 8, 144);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LowerThanLow', 1, 8, 175);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Aba Road', 1, 8, 122);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NeverWhatYouThink', 1, 8, 88);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WaitAMinuteGuys', 1, 8, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('OhBrother', 1, 8, 129);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('IRLNightmare', 1, 8, 137);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('StopDropAndRoll', 1, 8, 110);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WorstCaseScenario', 1, 8, 146);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LookWhatWeHaveHere', 1, 8, 86);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('PayItForward', 1, 8, 107);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TruthOfTheMatterIs', 1, 8, 179);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('AccountBalance', 1, 8, 82);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('PullTheSkyDown', 1, 8, 130);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('CryingThumbTacks&SpeakingInTongues', 1, 8, 139);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LivingSucks', 1, 9, 38);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Disinfected', 1, 9, 158);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NightShift', 1, 9, 151);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heathen', 1, 9, 132);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SG553', 1, 9, 121);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LavenderSkies', 1, 9, 58);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hazardous', 1, 9, 117);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ColdSideOfThePillow', 1, 9, 98);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TheLastTimeWeSpoke', 1, 9, 100);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('VideoHomeSystem', 1, 9, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ByTheSkinOfMyTeeth', 1, 9, 85);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('DoNotTryThisAtHome', 1, 9, 56);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ItsAllYourFault', 1, 9, 75);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BaptizeMeInTheSmoke', 1, 9, 116);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Troubleshooting', 1, 9, 108);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TopChoiceMeats', 1, 9, 444);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('PaidProgramming2', 1, 10, 72);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Rocks', 1, 10, 133);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TheCurseOfTheGhost', 1, 10, 145);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Biodegradable', 1, 10, 226);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ArtVandelay', 1, 10, 286);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NonPasteurized', 1, 10, 152);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('PeteyPablo', 1, 10, 94);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Maggots', 1, 10, 142);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SeeMeAfterClass', 1, 10, 72);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Maggots', 1, 10, 255);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SCENE 2', 11, 23, 181);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FIGHT', 11, 23, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SWEET', 11, 23, 202);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('GAMBA', 11, 23, 170);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SUNNY', 11, 23, 204);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SUMMER', 11, 23, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('introduction', 12, 24, 102);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ex Bitch', 12, 24, 121);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('UGLY', 12, 24, 91);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Triumph', 12, 24, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('before i realize', 12, 24, 94);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ATTENTION!', 12, 24, 148);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SeeMeAfterClass', 1, 10, 323);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('DeletedScenes', 1, 10, 83);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MineralWashed', 1, 10, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MyHeadHurt,INeedToLieDown', 1, 10, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('DeletedScenes', 1, 10, 83);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MineralWashed', 1, 10, 112);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MyHeadHurt,INeedToLieDown', 1, 10, 94);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('YourMusicSucksAndYouLookLikeADickhead', 1, 10, 84);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MyBiggestEnemyHasAlwaysBeenMyself', 1, 10, 87);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('YouAreNotNeeded,NoneOfUsAre', 1, 10, 85);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MagentaLavaLamp', 1, 10, 61);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Timeless', 1, 10, 122);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LivingstonCountyLegend', 1, 10, 226);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WordsCannotEncapsulate', 1, 10, 265);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TearsOfAnEagle', 1, 10, 155);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('AwayFromKeyboard', 1, 10, 205);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FinalLevelCutScene', 1, 10, 265);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SeshRadio_Volume3', 1, 10, 85);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dream On', 7, 11, 265);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Shine', 7, 11, 332);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Sweetest Condition', 7, 11, 216);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('When the Body Speaks', 7, 11, 363);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Dead of Night', 7, 11, 246);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lovetheme', 7, 11, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Freelove', 7, 11, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Comatose', 7, 11, 264);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Feel Loved', 7, 11, 335);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Breathe', 7, 11, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Easy Tiger', 7, 11, 332);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Am You', 7, 11, 236);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Goodnight Lovers', 7, 11, 334);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Dead of Night', 7, 11, 236);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Sweetest Condition', 7, 11, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dirt', 7, 11, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Zenstation', 7, 11, 283);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Never Let Me Down Again', 7, 12, 287);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Things You Said', 7, 12, 239);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Strangelove', 7, 12, 294);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Sacred', 7, 12, 286);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Little 15', 7, 12, 256);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Behind the Wheel', 7, 12, 345);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Want You Now', 7, 12, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('To Have and to Hold', 7, 12, 171);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Nothing', 7, 12, 285);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Pimpf', 7, 12, 287);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Agent Orange', 7, 12, 309);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Pleasure, Little Treasure', 7, 12, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Route 66', 7, 12, 275);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stjarna', 7, 12, 294);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Disorder', 8, 13, 209);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Day of the Lords', 8, 13, 287);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Candidate', 8, 13, 187);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Insight', 8, 13, 266);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('New Dawn Fades', 8, 13, 291);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dust', 8, 13, 237);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Shadowplay', 8, 13, 233);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wilderness', 8, 13, 160);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Interzone', 8, 13, 132);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Remember Nothing', 8, 13, 355);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Atrocity Exhibition', 8, 14, 364);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Isolation', 8, 14, 175);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Passover', 8, 14, 285);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Colony', 8, 14, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('A Means to an End', 8, 14, 249);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heart and Soul', 8, 14, 353);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Twenty Four Hours', 8, 14, 268);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Eternal', 8, 14, 364);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Decades', 8, 14, 374);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dead Souls', 8, 14, 299);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Glass', 8, 14, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('A Means to an End', 8, 14, 240);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Insight', 8, 14, 246);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Colony', 8, 14, 241);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('These Days', 8, 14, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Love Will Tear Us Apart', 8, 14, 257);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Isolation', 8, 14, 253);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Eternal', 8, 14, 281);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Digital', 8, 14, 270);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Ringer', 9, 15, 337);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Greatest', 9, 15, 227);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lucky You', 9, 15, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Paul', 9, 15, 35);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Normal', 9, 15, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Em Calls Paul', 9, 15, 49);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stepping Stone', 9, 15, 309);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Not Alike', 9, 15, 288);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Kamikaze', 9, 15, 216);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Fall', 9, 15, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Nice Guy', 9, 15, 150);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Good Guy', 9, 15, 142);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Venom', 9, 15, 260);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Bad Guy', 9, 16, 434);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Parking Lot', 9, 16, 55);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Rhyme Or Reason', 9, 16, 301);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Survival', 9, 16, 261);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Legacy', 9, 16, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Berzerk', 9, 16, 296);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Rap God', 9, 16, 410);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Brainless', 9, 16, 299);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stronger Than I Was', 9, 16, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('So Far...', 9, 16, 286);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Headlights', 9, 16, 345);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Evil Twin', 9, 16, 250);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Baby', 9, 16, 317);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Desperation', 9, 16, 356);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Groundhog Day', 9, 16, 293);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wicked Ways', 9, 16, 331);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Public Service Announcement 2000', 9, 17, 46);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Kill You', 9, 17, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Who Knew', 9, 17, 382);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Way I Am', 9, 17, 356);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Real Slim Shady', 9, 17, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Remember Me', 9, 17, 227);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I''m Back', 9, 17, 344);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Marshall Mathers', 9, 17, 322);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Drug Ballad', 9, 17, 80);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Kim', 9, 17, 377);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Criminal', 9, 17, 319);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Livewire', 10, 18, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Body Gold', 10, 18, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Technicolour Beat', 10, 18, 180);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Drive', 10, 18, 196);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lose It', 10, 18, 230);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Landslide', 10, 18, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('White Blood', 10, 18, 257);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Without You', 10, 18, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Rain', 10, 18, 174);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dazzle', 10, 18, 185);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All We Do', 10, 18, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Midnight Moon', 10, 18, 210);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Shark', 10, 18, 188);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heart Hope', 10, 18, 249);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Plans', 10, 18, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Solo', 10, 19, 205);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ultralife', 10, 19, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lifetimes', 10, 19, 232);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('High On Humans', 10, 19, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All About You', 10, 19, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heavy', 10, 19, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Bigger Than Love', 10, 19, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heart Strings', 10, 19, 204);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Slip Away', 10, 19, 221);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Overgrown', 10, 19, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My Friends', 10, 19, 295);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Waste', 10, 19, 256);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NO HALO', 11, 20, 259);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SUGAR', 11, 20, 204);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BOY BYE', 11, 20, 142);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('HEAVEN BELONGS TO YOU', 11, 20, 89);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ST. PERCY', 11, 20, 210);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('IF YOU PRAY RIGHT', 11, 20, 302);
INSERT INTO Track (title, artistId, albumId, duration) VALUES (' DEARLY DEPARTED', 11, 20, 280);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I BEEN BORN AGAIN', 11, 20, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('GINGER', 11, 20, 234);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BIG BOY', 11, 20, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LOVE ME FOR LIFE', 11, 20, 215);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('VICTOR ROBERTS', 11, 20, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NEW ORLEANS', 11, 21, 243);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('THUG LIFE', 11, 21, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BERLIN', 11, 21, 199);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SOMETHING ABOUT HIM', 11, 21, 93);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WHERE THE CASH AT', 11, 21, 234);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WEIGHT', 11, 21, 260);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('DISTRICT', 11, 21, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('LOOPHOLE', 11, 21, 53);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TAPE', 11, 21, 209);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('J''OUVERT', 11, 21, 234);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('HONEY', 11, 21, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('VIVID', 11, 21, 144);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SAN MARCOS', 11, 21, 286);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TONYA', 11, 21, 283);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FABRIC', 11, 21, 277);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('HEAT', 11, 22, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('GOLD', 11, 22, 266);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('STAR', 11, 22, 161);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BOYS', 11, 22, 278);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('2PAC', 11, 22, 62);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SKIT 1', 11, 22, 19);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FAKE', 11, 22, 275);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BANK', 11, 22, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SKIT 2', 11, 22, 15);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TRIP', 11, 22, 202);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SWIM', 11, 22, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('BUMP', 11, 22, 158);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('CASH', 11, 22, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SKIT 3', 11, 22, 39);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('MILK', 11, 22, 295);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FACE', 11, 22, 259);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WASTE', 11, 22, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('GUMMY', 11, 23, 261);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('QUEER', 11, 23, 227);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('JELLO', 11, 23, 80);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TEETH', 11, 23, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SWAMP', 11, 23, 39);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SCENE', 11, 23, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('TOKYO', 11, 23, 80);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('JESUS', 11, 23, 204);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('CHICK', 11, 23, 248);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('JUNKY', 11, 23, 30);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Eat It Up', 12, 24, 60);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('HEARTEATER', 12, 24, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('numb the pain', 12, 24, 107);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Introduction (instructions)', 12, 25, 117);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ALONE, PART 3', 12, 25, 110);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Moonlight', 12, 25, 135);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('SAD!', 12, 25, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('the remedy for a broken heart', 12, 25, 160);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Floor 555', 12, 25, 93);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NUMB', 12, 25, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('going down!', 12, 25, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('love yourself', 12, 25, 115);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('changes', 12, 25, 101);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('changes', 12, 25, 70);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hope', 12, 25, 168);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('schizophrenia', 12, 25, 63);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('before I close my eyes', 12, 25, 105);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Nocturne', 12, 25, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hope', 12, 25, 127);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Jah on drums', 12, 25, 144);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('A GHETTO CHRISTMAS CAROL', 12, 25, 204);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('hate will never win', 12, 25, 94);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('UP LIKE AN INSOMNIAC', 12, 25, 179);
INSERT INTO Track (title, artistId, albumId, duration) VALUES (' Red Light!', 12, 25, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Indecision', 12, 25, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Explanation', 12, 26, 50);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Jocelyn Flores', 12, 26, 119);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Depression & Obsession', 12, 26, 144);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Everybody Dies In Their Nightmares', 12, 26, 95);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Revenge', 12, 26, 120);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Save Me', 12, 26, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dead Inside (Interlude)', 12, 26, 86);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Fuck Love', 12, 26, 146);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Carry On', 12, 26, 129);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Orlando', 12, 26, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ayala', 12, 26, 99);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Лоси', 13, 27, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Душ', 13, 27, 286);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Столярка', 13, 27, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Чебурашка', 13, 27, 185);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Голова', 13, 27, 215);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Пожар', 13, 27, 131);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Холодок', 13, 27, 171);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Москва-область', 13, 27, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Вишенка', 13, 27, 234);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Наёк ёк', 13, 27, 137);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Злые голуби', 13, 27, 233);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Память', 13, 28, 179);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Пора домой', 13, 28, 106);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Овощ', 13, 28, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Весна', 13, 28, 115);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Куртец', 13, 28, 240);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Молния', 13, 28, 174);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Думай позитивно', 13, 28, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Представьте', 13, 28, 132);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ужален', 13, 28, 143);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Генетика', 13, 28, 110);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Душно', 13, 28, 209);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Деревня', 13, 28, 267);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Цветы в вазе', 13, 28, 142);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ребята', 13, 28, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Интро', 13, 29, 55);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Зимняя', 13, 29, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Быть плохим', 13, 29, 117);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Колхозники', 13, 29, 113);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Беспорядки', 13, 29, 188);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Гантеля', 13, 29, 231);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Органы', 13, 29, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Глаза', 13, 29, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ночь', 13, 29, 120);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Метадон', 13, 29, 218);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Киса', 13, 29, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Шурик', 13, 29, 168);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Аутро', 13, 29, 130);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('She''s Thunderstorms', 14, 30, 234);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Black Treacle', 14, 30, 217);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Brick By Brick', 14, 30, 179);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Hellcat Spangled Shalalala', 14, 30, 180);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Library Pictures', 14, 30, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All My Own Stunts', 14, 30, 142);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Reckless Serenade', 14, 30, 232);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Piledriver Waltz', 14, 30, 282);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Love is a Laserquest', 14, 30, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Suck It and See', 14, 30, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('That''s Where You''re Wrong', 14, 30, 226);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Star Treatment', 14, 31, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('One Point Perspective', 14, 31, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('American Sports', 14, 31, 173);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Tranquility Base Hotel & Casino', 14, 31, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Golden Trunks', 14, 31, 300);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Four Out Of Five', 14, 31, 305);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The World''s First Ever Monster Truck Front Flip', 14, 31, 242);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Science Fiction', 14, 31, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('She Looks Like Fun', 14, 31, 277);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Batphone', 14, 31, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Ultracheese', 14, 31, 296);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Do I Wanna Know?', 14, 32, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('R U Mine?', 14, 32, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('One For The Road', 14, 32, 206);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Arabella', 14, 32, 207);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Want It All', 14, 32, 185);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('No1 Party Anthem', 14, 32, 243);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Mad Sounds', 14, 32, 215);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Fireside', 14, 32, 181);
INSERT INTO Track (title, artistId, albumId, duration) VALUES (' Why''d You Only Call Me When You''re High?', 14, 32, 161);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Snap Out Of It', 14, 32, 193);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Knee Socks', 14, 32, 257);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Wanna Be Yours', 14, 32, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Young at Heart', 15, 33, 125);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Three Coins in the Fountain', 15, 33, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Learnin'' the Blues', 15, 33, 120);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Love and Marriage', 15, 33, 218);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Love Is the Tender Trap', 15, 33, 169);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Well Did You Evah', 15, 33, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hey, Jealous Lover', 15, 33, 124);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Makin'' Whoopie', 15, 33, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('You, My Love', 15, 33, 181);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Not as a Stranger', 15, 33, 148);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Melody of Love', 15, 33, 158);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Same Old Saturday Night', 15, 33, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('How Little It Matters', 15, 33, 181);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('South of the Border', 15, 33, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Gal That Got Away', 15, 33, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My One and Only Love', 15, 33, 155);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Don''T Worry ''Bout Me', 15, 33, 225);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I''M Walking Behind You', 15, 33, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('You Brought a New Kind of Love to Me', 15, 33, 223);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lean Baby', 15, 33, 144);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Get a Kick out of You', 15, 33, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('You Make Me Feel so Young', 15, 33, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('In the Wee Small Hours of the Morning', 15, 33, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I''Ve Got the World on a String', 15, 33, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('You’Re Getting to Be a Habit with Me', 15, 33, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I''Ve Got You Under My Skin', 15, 33, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('A Foggy Day', 15, 33, 125);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My Funny Valentine', 15, 33, 126);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I''M Gonna Sit Right Down', 15, 33, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('From Here to Eternity', 15, 33, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('It Happened in Monterey', 15, 33, 155);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('How About You', 15, 33, 145);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('They Can’T Take That Away from Me', 15, 33, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Someone to Watch over Me', 15, 33, 152);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Get Happy', 15, 33, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All of Me', 15, 33, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Mood Indigo', 15, 33, 129);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('When Your Lover Has Gone', 15, 33, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Too Marvellous for Words', 15, 33, 187);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Anything Goes', 15, 33, 256);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Кукушка', 16, 34, 392);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Звезда по имени Солнце', 16, 34, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Группа крови', 16, 34, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Место для шага вперёд', 16, 34, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Пачка сигарет', 16, 34, 343);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Красно-жёлтые дни', 16, 34, 414);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Кончится лето', 16, 34, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Последний герой', 16, 34, 233);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('В наших глазах', 16, 34, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Хочу перемен', 16, 34, 343);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Муравейник', 16, 34, 405);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Печаль', 16, 34, 332);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Когда твоя девушка больна', 16, 34, 343);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Закрой за мной дверь, я ухожу', 16, 34, 234);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Стук', 16, 34, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Спокойная ночь', 16, 34, 323);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Звезда', 16, 34, 404);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Песня без слов', 16, 34, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Следи за собой', 16, 34, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Попробуй спеть вместе со мной', 16, 34, 304);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Война', 16, 34, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Дальше действовать будем мы', 16, 34, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Нам с тобой', 16, 34, 305);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Мама, мы все сошли с ума', 16, 34, 247);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Мама-анархия', 16, 34, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Видели ночь', 16, 34, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Алюминиевые огурцы', 16, 34, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Невёселая песня', 16, 34, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Бошетунмай', 16, 34, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Троллейбус', 16, 34, 131);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Фильмы', 16, 34, 284);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Прохожий', 16, 34, 311);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Это не любовь', 16, 34, 394);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Жизнь в стёклах', 16, 34, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Весна', 16, 34, 452);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Восьмиклассница', 16, 34, 241);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Камчатка', 16, 34, 383);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Каждую ночь', 16, 34, 198);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Электричка', 16, 34, 319);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Рядом со мной', 16, 34, 412);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Мама, мы все тяжело больны', 16, 34, 247);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('antistereo', 2, 2, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('starfall', 2, 2, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('pretty when u cry', 2, 2, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('green-eyed taxi', 2, 2, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Filament', 2, 3, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Passion', 2, 3, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Readiness', 2, 3, 265);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Looking for', 2, 3, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Melancholy', 2, 3, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Return stroke', 2, 3, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dekstop', 2, 3, 205);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('mist', 2, 2, 189);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('pause', 2, 2, 250);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('later', 2, 2, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('на заре', 2, 2, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('THE SAME', 2, 2, 212);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('it''s a feeling', 2, 2, 251);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('observer', 2, 2, 200);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('memento mori', 2, 2, 188);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('another world is dying near you', 2, 2, 276);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('again', 2, 2, 217);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('no way', 2, 2, 226);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('insight', 2, 2, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('the push', 2, 2, 233);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('factor', 2, 2, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('in point of fact', 2, 2, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('take u away', 2, 2, 205);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('wearout', 2, 2, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('playing with fire', 2, 2, 207);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('do u like this game?', 2, 4, 236);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('reboot', 2, 4, 168);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('complete', 2, 4, 242);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('nightmare 2', 2, 4, 236);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('sorry (vs. Madonna)', 2, 2, 190);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('mute scream', 2, 2, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('np-oh/mp', 2, 2, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('soon', 2, 5, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('nothing', 2, 5, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('prehistory', 2, 5, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('credo', 2, 5, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('leftover', 2, 5, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('story of Douan', 2, 5, 282);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('nona', 2, 5, 285);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Winter', 3, 5, 249);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('DISTANCE', 4, 2, 226);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('voice', 2, 5, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('md.', 2, 5, 197);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('unrealised [5113]', 2, 5, 231);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('here', 2, 5, 168);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('807. From Past', 2, 5, 122);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('yourself', 2, 5, 136);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('stress', 2, 5, 248);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('where are we?', 2, 5, 168);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('dream', 2, 5, 180);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('nightmare', 2, 5, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('unlike', 2, 5, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('забирай меня скорей (vs. Руки Вверх)', 2, 5, 228);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('not gonna get us (vs. Tatu)', 2, 5, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('philosophy (vs. Tom Snare)', 2, 5, 336);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('dance, bitch', 2, 5, 218);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('nobody', 2, 5, 143);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('face', 2, 5, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('goodbye', 2, 5, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('sunset', 2, 5, 116);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('cyberdisco', 2, 2, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('2405', 2, 2, 93);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('nostalgia', 2, 5, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('overload', 2, 5, 193);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('overload II', 2, 5, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('rainy evening', 2, 5, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('bfts17\_01', 2, 2, 231);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('16477', 2, 2, 92);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('fragile', 2, 2, 120);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('sindrom 2006', 2, 5, 177);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('vagabond', 2, 5, 196);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('live', 2, 5, 196);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('rain, river', 2, 5, 205);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('call me', 2, 5, 164);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('dreamline', 2, 5, 312);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('22b', 2, 5, 78);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('closed', 2, 5, 170);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('⍏r∆Iñ', 2, 5, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('dark маск', 2, 5, 200);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('колея', 2, 2, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('-||-', 2, 5, 268);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ne', 2, 2, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('dust', 2, 5, 231);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('to give this song (vs.Vitas)', 2, 5, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('VIII', 2, 5, 132);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('wrong way', 2, 2, 166);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('молодость', 2, 2, 93);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('53201', 2, 5, 129);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('visitor', 2, 5, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('don''t touch', 2, 2, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('pathetic', 2, 5, 228);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('unrealised [spl]', 2, 5, 136);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('블라인드 세계', 2, 5, 270);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('YOUR STYLE', 2, 5, 205);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('e.m.s.p.', 2, 5, 103);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('everybody is fucking tired (vs. Sco)', 2, 5, 202);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('you are', 2, 2, 218);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('в сон после пробуждения', 2, 5, 96);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('помолился и в клуб', 2, 5, 77);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('think about', 2, 5, 70);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('demon', 2, 5, 127);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('breath', 2, 5, 314);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('at night', 2, 5, 121);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('unrealised', 2, 5, 107);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('вечерняя волна', 2, 5, 240);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('VI (утро в чужом городе)', 2, 5, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('unfinished', 2, 5, 104);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('and what', 2, 5, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('suicide lazy town', 2, 5, 220);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('simply II', 2, 5, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('escape from mirror', 2, 5, 207);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('IX', 2, 5, 237);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('X', 2, 5, 175);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('exit', 5, 5, 228);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('outro', 2, 5, 290);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('without reality', 2, 5, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('simply', 2, 5, 311);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('all things (the cinematic orchestra)', 2, 5, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('solace', 2, 5, 80);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('impulse', 2, 5, 220);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('motion', 2, 5, 241);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('symptoms', 2, 5, 198);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('the way', 2, 5, 279);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('no', 2, 5, 197);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('moron', 2, 5, 239);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('no sleep', 2, 5, 268);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('running', 2, 5, 294);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('waiting', 2, 5, 323);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('rest', 2, 5, 202);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('the second', 2, 5, 235);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('like this', 2, 5, 226);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('tragedy', 2, 5, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('EMPTY', 2, 5, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('пl3nkv', 2, 5, 143);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('REUNION', 2, 5, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FEAR', 2, 5, 85);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('IMAGINE', 2, 5, 273);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ALC.', 2, 5, 210);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('COLORS', 2, 5, 196);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('crazy 1995', 2, 5, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('ਦੋ ਵਜੇ', 2, 5, 228);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stratosphere', 6, 5, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('another world', 2, 5, 271);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('but sad', 2, 5, 199);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lost Hope', 6, 5, 210);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('deep memory', 2, 5, 218);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('sweet sixteen', 2, 5, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Illusion', 2, 5, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Nightwalk', 2, 5, 260);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Mirrors', 2, 5, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('morning', 2, 5, 114);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('choices', 2, 5, 193);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hung up (vs. Madonna)', 2, 5, 210);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('feel it', 2, 5, 328);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('просто смотрю на мир', 2, 5, 254);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('near me', 2, 5, 210);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('gabba vibes (vs. Kaigerda)', 2, 5, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('mood move', 2, 5, 287);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('get a sign', 2, 5, 240);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('exotic', 2, 5, 104);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('asleep', 2, 5, 168);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('love me', 2, 5, 256);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('lose', 2, 5, 229);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Время есть, а денег нет', 16, 34, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Сказка', 16, 34, 185);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Апрель', 16, 34, 305);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Я объявляю свой дом', 16, 34, 302);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ночь', 16, 34, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Бездельник', 16, 34, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Просто хочешь ты знать', 16, 34, 223);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Разpеши мне', 16, 34, 294);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ты мог бы', 16, 34, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Лето', 16, 34, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Дети проходных дворов', 16, 34, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Любовь это не шутка', 16, 34, 324);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ты обвела меня вокруг пальца', 16, 34, 294);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Игра', 16, 34, 392);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Мои друзья', 16, 34, 223);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Дерево', 16, 34, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Раньше в твоих глазах', 16, 34, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Сосны на морском берегу', 16, 34, 302);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Музыка волн', 16, 34, 132);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Транквилизатор', 16, 34, 314);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Прогулка романтика', 16, 34, 381);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Дождь для нас', 16, 34, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Генерал', 16, 34, 312);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Малыш', 16, 34, 225);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Уходи', 16, 34, 141);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Братская любовь', 16, 34, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Солнечные дни', 16, 34, 246);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Танец', 16, 34, 368);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Звёзды останутся здесь', 16, 34, 309);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Город', 16, 34, 366);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Проснись', 16, 34, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ситар играл', 16, 34, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Мне не нравится город Москва', 16, 34, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Мы хотим танцевать', 16, 34, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Хочу быть с тобой', 16, 34, 312);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Я хочу быть кочегаром', 16, 34, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Твой номер', 16, 34, 312);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Я иду по улице', 16, 34, 403);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Перекати-поле', 16, 34, 296);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('На кухне', 16, 34, 332);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Когда-то ты был битником', 16, 34, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Легенда', 16, 34, 223);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Warm On A Cold Night', 17, 35, 261);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Til The Evening', 17, 35, 280);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Someone That Loves You', 17, 35, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All In The Value', 17, 35, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Treat You Right', 17, 35, 294);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Out Of My Control', 17, 35, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Coastal Love', 17, 35, 256);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('It Ain''t Wrong Loving You', 17, 35, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Night', 17, 35, 348);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Good Together', 17, 35, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('One At A Time Please', 17, 35, 270);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('FHKD', 17, 35, 248);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Take You High', 17, 35, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Might', 17, 36, 254);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Me & You', 17, 36, 251);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Day 1', 17, 36, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Got You', 17, 36, 240);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Feels So Good', 17, 36, 197);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('306', 17, 36, 267);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Location Unknown', 17, 36, 199);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Crying Over You', 17, 36, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Shrink', 17, 36, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Just Wanna Go Back', 17, 36, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Sometimes', 17, 36, 285);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Forget Me Not', 17, 36, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('How', 18, 37, 312);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Afraid', 18, 37, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Everybody''s Watching Me', 18, 37, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Sweater Weather', 18, 37, 293);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Let It Go', 18, 37, 293);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Alleyways', 18, 37, 186);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Flawless', 18, 37, 259);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Female Robbery', 18, 37, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Staying Up', 18, 37, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Float', 18, 37, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dust', 18, 38, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Kill Us All', 18, 38, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('43670', 18, 38, 221);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Scary Love', 18, 38, 224);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Softcore', 18, 38, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Void', 18, 38, 2063);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Roll Call', 18, 38, 130);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('You Get Me So High', 18, 38, 251);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Reflections', 18, 38, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Blue', 18, 38, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Paradise', 18, 38, 190);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Beat Take 1', 18, 38, 149);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stuck with Me', 18, 38, 208);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Flowers', 18, 38, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Compass', 18, 38, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Noise', 18, 38, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heaven', 18, 38, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Nervous', 18, 38, 242);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Sadderdaze', 18, 38, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Beautiful Oblivion', 18, 38, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('NSTYNCT', 18, 39, 253);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lurk', 18, 39, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Jealou$y', 18, 39, 343);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('1 of those Weaks', 18, 39, 261);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('YG call', 18, 39, 212);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('When I Get Back', 18, 39, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('To', 18, 39, 56);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Rain', 18, 39, 212);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('icanteven', 18, 39, 162);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('U&I', 18, 39, 162);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Givin & Takin', 18, 39, 114);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Unfair', 18, 39, 202);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Silver', 18, 39, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('T$RL', 18, 39, 209);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Changeling', 19, 40, 259);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Love Her Madly', 19, 40, 198);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Been down so Long', 19, 40, 279);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Cars Hiss by My Window', 19, 40, 249);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('L.A. Woman', 19, 40, 291);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('America', 19, 40, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hyacinth House', 19, 40, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Crawling King Snake', 19, 40, 299);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The WASP', 19, 40, 254);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Riders on the Storm', 19, 40, 434);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Roadhouse Blues', 19, 41, 243);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Waiting for the Sun', 19, 41, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('You Make Me Real', 19, 41, 171);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Peace Frog', 19, 41, 298);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Blue Sunday', 19, 41, 190);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ship of Fools', 19, 41, 128);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Land Ho!', 19, 41, 249);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Spy', 19, 41, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Queen of the Highway', 19, 41, 167);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Indian Summer', 19, 41, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Maggie MGill', 19, 41, 204);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hello, I Love You', 19, 42, 133);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Love Street', 19, 42, 169);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Not to Touch the Earth', 19, 42, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Summer''s Almost Gone', 19, 42, 139);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wintertime Love', 19, 42, 172);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Unknown Soldier', 19, 42, 201);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Spanish Caravan', 19, 42, 298);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My Wild Love', 19, 42, 179);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('We Could Be so Good Together', 19, 42, 143);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Yes, the River Knows', 19, 42, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Five to One', 19, 42, 145);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Break On Through', 19, 43, 145);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Soul Kitchen', 19, 43, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Crystal Ship', 19, 43, 152);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Twentieth Century Fox', 19, 43, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Alabama Song', 19, 43, 437);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Light My Fire', 19, 43, 129);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Back Door Man', 19, 43, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Looked At You', 19, 43, 140);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('End Of The Night', 19, 43, 170);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Take It As It Comes', 19, 43, 135);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The End', 19, 43, 703);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All I Have', 20, 44, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wake Up', 20, 44, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hands Up', 20, 44, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Only One', 20, 44, 223);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Thing Called Love', 20, 44, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Just Being Me', 20, 44, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Intro', 20, 45, 243);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Mansion', 20, 45, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All I Have', 20, 45, 243);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wait', 20, 45, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wake Up', 20, 45, 242);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Face It', 20, 45, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Motivated', 20, 45, 122);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Notepad', 20, 45, 243);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Turn The Music Up', 20, 45, 304);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Paralyzed', 20, 45, 182);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Intro 2', 20, 46, 125);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Therapy Session', 20, 46, 244);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Just Wanna Know', 20, 46, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('How Could You Leave Us', 20, 46, 242);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Breathe', 20, 46, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Real', 20, 46, 185);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Oh Lord', 20, 46, 245);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Can Feel It', 20, 46, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Got You On My Mind', 20, 46, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Grindin''', 20, 46, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wish You Wouldn''t', 20, 46, 242);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Statement', 20, 46, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('All I Do', 20, 46, 184);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Lost In The Moment', 20, 46, 125);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Search', 20, 47, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Leave Me Alone', 20, 47, 315);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Change', 20, 47, 211);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My Stress', 20, 47, 286);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Nate', 20, 47, 202);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Time', 20, 47, 258);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Returns', 20, 47, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('When I Grow Up', 20, 47, 258);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Only', 20, 47, 233);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Let Me Go', 20, 47, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Interlude', 20, 47, 277);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hate Myself', 20, 47, 346);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Miss The Days', 20, 47, 191);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('No Excuses', 20, 47, 263);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Like This', 20, 47, 154);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Options', 20, 47, 264);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('WHY', 20, 47, 143);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Thinking', 20, 47, 285);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Trauma', 20, 47, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Time ', 20, 47, 283);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Power Of Equality', 21, 48, 176);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('If You Have To Ask', 21, 48, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Breaking The Girl', 21, 48, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Funky Monks', 21, 48, 282);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Suck My Kiss', 21, 48, 354);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Could Have Lied', 21, 48, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Mellowship Slinky In B Major', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Righteous & The Wicked', 21, 48, 269);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Give It Away', 21, 48, 199);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Blood Sugar Sex Magik', 21, 48, 258);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Under The Bridge', 21, 48, 339);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Naked In The Rain', 21, 48, 369);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Apache Rose Peacock', 21, 48, 291);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Greeting Song', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My Lovely Man', 21, 48, 334);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Sir Psycho Sexy', 21, 48, 239);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Warped', 21, 48, 314);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Aeroplane', 21, 48, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Deep Kick', 21, 48, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('My Friends', 21, 48, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Coffee Shop', 21, 48, 291);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Pea', 21, 48, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('One Big Mob', 21, 48, 310);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Walkabout', 21, 48, 188);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Tearjerker', 21, 48, 309);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('One Hot Minute', 21, 48, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Falling Into Grace', 21, 48, 347);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Shallow Be Thy Game', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Transcending', 21, 48, 324);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Around The World', 21, 48, 193);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Parallel Universe', 21, 48, 289);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Scar Tissue', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Otherside', 21, 48, 319);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Get On Top', 21, 48, 232);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Californication', 21, 48, 261);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Easily', 21, 48, 178);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Porcelain', 21, 48, 299);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Emit Remmus', 21, 48, 203);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Like Dirt', 21, 48, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('This Velvet Glove', 21, 48, 325);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Savior', 21, 48, 145);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Purple Stain', 21, 48, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Right On Time', 21, 48, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Road Tripping', 21, 48, 151);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('By The Way', 21, 48, 317);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Universally Speaking', 21, 48, 189);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('This Is The Place', 21, 48, 165);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dosed', 21, 48, 260);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Don''t Forget Me', 21, 48, 230);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Zephyr Song', 21, 48, 315);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Can''t Stop', 21, 48, 223);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('I Could Die For You', 21, 48, 374);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Midnight', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Throw Away Your Television', 21, 48, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Cabron', 21, 48, 163);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Tear', 21, 48, 252);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('On Mercury', 21, 48, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Minor Thing', 21, 48, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Warm Tape', 21, 48, 296);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Venice Queen', 21, 48, 332);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dani California', 21, 48, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Snow (Hey Oh)', 21, 48, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Charlie', 21, 48, 414);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stadium Arcadium', 21, 48, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hump de Bump', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('She''s Only 18', 21, 48, 329);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Slow Cheetah', 21, 48, 199);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Torture Me', 21, 48, 378);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Strip My Mind', 21, 48, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Especially In Michigan', 21, 48, 309);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Warlocks', 21, 48, 351);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('C''mon Girl', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Wet Sand', 21, 48, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hey', 21, 48, 359);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Desecration Smile', 21, 48, 374);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Tell Me Baby', 21, 48, 194);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Hard To Concentrate', 21, 48, 303);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('21st Century', 21, 48, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('She Looks To Me', 21, 48, 351);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Readymade', 21, 48, 238);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Readymade', 21, 48, 310);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('If', 21, 48, 308);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Make You Feel Better', 21, 48, 249);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Animal Bar', 21, 48, 255);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('So Much I', 21, 48, 347);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Storm In A Teacup', 21, 48, 334);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('We Believe', 21, 48, 384);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Turn It Again', 21, 48, 313);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Death Of A Martian', 21, 48, 349);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Monarchy Of Roses', 21, 48, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Factory Of Faith', 21, 48, 259);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Brendan''s Death Song', 21, 48, 352);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ethiopia', 21, 48, 261);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Annie Wants A Baby', 21, 48, 358);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Look Around', 21, 48, 299);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Adventures Of Rain Dance Maggie', 21, 48, 383);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Did I Let You Know', 21, 48, 334);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Goodbye Hooray', 21, 48, 445);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Happiness Loves Company', 21, 48, 145);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Police Station', 21, 48, 213);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Even You Brutus?', 21, 48, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Meet Me At The Corner', 21, 48, 331);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Dance, Dance, Dance', 21, 48, 197);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Blossom', 22, 49, 189);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Ego', 22, 49, 285);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Firebird', 22, 49, 200);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Doing Good', 22, 49, 350);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Clouds', 22, 49, 195);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Cold Blue Rain', 22, 49, 283);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Stay', 22, 49, 134);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Bad Things', 22, 49, 274);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Cocoon', 22, 49, 192);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Losing You', 22, 49, 283);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Peripeteia', 22, 49, 312);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Alive', 22, 49, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Piano Song', 22, 49, 183);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Heartless', 22, 49, 296);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Fado', 22, 50, 152);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Oh Mama', 22, 50, 342);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('The Game', 22, 50, 222);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Rush', 22, 50, 174);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Long Run', 22, 50, 262);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Daydreaming', 22, 50, 214);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('We Didn''t Make It To The Moon', 22, 50, 329);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Eden''s House', 22, 50, 199);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Scarlet Paintings', 22, 50, 378);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Right From Here', 22, 50, 219);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Fallen', 22, 50, 272);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Window', 22, 50, 123);
INSERT INTO Track (title, artistId, albumId, duration) VALUES ('Bad Things', 22, 50, 242);